/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: 'hsl(210, 100%, 97%)',
          100: 'hsl(210, 96%,  93%)',
          200: 'hsl(210, 90%,  84%)',
          300: 'hsl(210, 86%,  72%)',
          400: 'hsl(210, 88%,  60%)',
          500: 'hsl(210, 92%,  48%)',
          600: 'hsl(214, 90%,  40%)',
          700: 'hsl(218, 88%,  32%)',
          800: 'hsl(220, 84%,  26%)',
          900: 'hsl(222, 80%,  18%)',
          950: 'hsl(224, 78%,  12%)',
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          400: 'hsl(268, 80%, 62%)',
          500: 'hsl(268, 76%, 52%)',
          600: 'hsl(269, 72%, 44%)',
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          400: 'hsl(160, 64%, 48%)',
          500: 'hsl(160, 60%, 38%)',
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "var(--success)",
          bg: "var(--success-bg)",
          text: "var(--success-text)",
          border: "var(--success-border)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          bg: "var(--warning-bg)",
          text: "var(--warning-text)",
          border: "var(--warning-border)",
        },
        danger: {
          DEFAULT: "var(--danger)",
          bg: "var(--danger-bg)",
          text: "var(--danger-text)",
          border: "var(--danger-border)",
        },
        info: {
          DEFAULT: "var(--info)",
          bg: "var(--info-bg)",
          text: "var(--info-text)",
          border: "var(--info-border)",
        },
        profit: {
          DEFAULT: "var(--profit)",
          bg: "var(--profit-bg)",
          text: "var(--profit-text)",
        },
        loss: {
          DEFAULT: "var(--loss)",
          bg: "var(--loss-bg)",
          text: "var(--loss-text)",
        },
        neutral: {
          DEFAULT: "var(--neutral)",
          bg: "var(--neutral-bg)",
          text: "var(--neutral-text)",
        },
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        '2xl': "var(--radius-xl)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
        xs: "var(--radius-xs)",
        full: "var(--radius-full)",
      },
      fontFamily: {
        sans: ['Inter', 'SF Pro Display', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        caption: ['0.75rem', { lineHeight: '1rem' }],
        label: ['0.8125rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.625rem' }],
        h4: ['1.125rem', { lineHeight: '1.5rem' }],
        h3: ['1.25rem', { lineHeight: '1.75rem' }],
        h2: ['1.5rem', { lineHeight: '2rem' }],
        h1: ['2rem', { lineHeight: '2.25rem' }],
        display: ['2.5rem', { lineHeight: '2.75rem' }],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      spacing: {
        0: '0px',
        px: '1px',
        0.5: '0.125rem',
        1: '0.25rem',
        1.5: '0.375rem',
        2: '0.5rem',
        2.5: '0.625rem',
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        48: '12rem',
        64: '16rem',
      },
      zIndex: {
        base: '0',
        raised: '10',
        dropdown: '100',
        sticky: '200',
        overlay: '300',
        modal: '400',
        toast: '500',
        tooltip: '600',
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "toast-progress": {
          "from": { width: "100%" },
          "to": { width: "0%" },
        },
        "fade-in": {
          "from": { opacity: "0" },
          "to": { opacity: "1" },
        },
        "fade-in-up": {
          "from": { opacity: "0", transform: "translateY(8px)" },
          "to": { opacity: "1", transform: "translateY(0)" },
        },
        "modal-in": {
          "from": { opacity: "0", transform: "scale(0.96) translateY(8px)" },
          "to": { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        "toast-in": {
          "from": { opacity: "0", transform: "translateX(100%) scale(0.95)" },
          "to": { opacity: "1", transform: "translateX(0) scale(1)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.4s ease infinite",
        "toast-progress": "toast-progress linear forwards",
        "fade-in": "fade-in 0.18s ease-out both",
        "fade-in-up": "fade-in-up 0.25s ease-out both",
        "modal-in": "modal-in 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "toast-in": "toast-in 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
}
